name: nvsynthesis
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - pyyaml=6.0.2
  - pillow=10.4.0
  - opencv=4.10.*
  - tqdm=4.66.*
  - einops=0.8.*
  - pytz=2024.*
  - tensorboard=2.17.*
  - pip
